version: '3'

services:
  
  example:
    image: openwrtorg/rootfs:x86-64
    user: root
    working_dir: /www
    restart: always
    command: /sbin/init
    container_name: example
    ports:
      - 8080:8080
    volumes:
      - ./entrypoint.sh:/etc/rc.local
      - ./public:/www